version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/bin/docker:/usr/bin/docker"
    container_name: jenkins
volumes:
  jenkins_home:


# this docker compose file should be used in jenkins server to create a docker container for jenkins
# it should be done manually
# after running this file, jenkins will be available on port 8080
# we also need to avail docker commands inside jenkins container and for that we need to change permission for docker.sock file 

# chmod 666 /var/run/docker.sock # run this command as root user inside jenkins container